- name: Install K3s server
  hosts: servers
  tasks:
  - name: Install fronend
    kubernetes.core.helm:
      name: front
      chart_ref: ./helm-frontend/frontend-chart
      release_namespace: default
      force: True
      disable_hook: True
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      values: 
        replicaCount: 1
        image:
          repository: "{{ image_repository }}"
          tag: "{{ image_tag }}"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: "{{ service_port }}"
        env:
          BACKEND_URL: '{{ BACKEND_URL }}'
        ingress:
          enabled: true
          host: app.class-schedule.pp.ua
          path: /
          pathType: Prefix
          entryPoint: websecure
          tls:
            enabled: true
            secretName: tls-secret
      release_state: "{{ helm_release_state }}"
  - name: Check frontend pods are ready (retry until condition)
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: default
      label_selectors:
        - app=front
    register: frontend_pods
    until: >
      frontend_pods.resources | length > 0 and
      frontend_pods.resources | map(attribute='status.containerStatuses') | flatten() | selectattr('ready') | list | length == frontend_pods.resources | length
    retries: 30
    delay: 10