- name: Install K3s server
  hosts: servers
  tasks:
  - name: Install fronend
    kubernetes.core.helm:
      name: front
      chart_ref: ./helm-frontend/frontend-chart
      release_namespace: default
      force: True
      disable_hook: True
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      values: 
        replicaCount: 1
        image:
          repository: "{{ image_repository }}"
          tag: "{{ image_tag }}"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: "{{ service_port }}"
        env:
          BACKEND_URL: '{{ BACKEND_URL }}'
        ingress:
          enabled: true
          host: app.class-schedule.pp.ua
          path: /
          pathType: Prefix
          entryPoint: websecure
          tls:
            enabled: true
            secretName: tls-secret
      release_state: "{{ helm_release_state }}"
  - name: Wait for all pods in frontend deployment to be ready
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: default
      label_selectors:
        - app=front       
    register: frontend_pods

  - name: Fail if pods are not ready after waiting
    wait_until:
      timeout: 300       
      delay: 10         
      msg: "Waiting for frontend pods to be ready"
      state: succeeded
      condition: >
        frontend_pods.resources | length > 0 and
        frontend_pods.resources | map(attribute='status.containerStatuses') | flatten() | selectattr('ready') | list | length == frontend_pods.resources | length
