- name: Install K3s server
  hosts: servers
  tasks:
  - name: Install backend
    kubernetes.core.helm:
      name: back
      chart_ref: ./helm-backend/backend-chart
      release_namespace: default
      force: True
      disable_hook: True
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      values:
        replicaCount: 1
        image:
          repository: "{{ image_repository }}"
          tag: "{{ image_tag }}"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: "{{ service_port }}"
        env:
          DB_ENDPOINT: "{{ db_endpoint }}"
          DATABASE: "{{ database }}"
          USERNAME: "{{ username }}"
          USERPASSWORD: "{{ userpassword }}"
          CACHE_ENDPOINT: "{{ cache_endpoint }}"
        ingress:
          enabled: true
          host: back.class-schedule.pp.ua
          path: /
          pathType: Prefix
          entryPoint: websecure
          tls:
            enabled: true
            secretName: tls-secret
      release_state: "{{ helm_release_state }}"
  - name: Check backend pods status
    shell: |
      kubectl get pods -n default -l app=backend -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.phase}{"\n"}{end}'
    register: pod_status

  - debug:
      msg: "{{ pod_status.stdout }}"
  
