  - name: Install fronend
    kubernetes.core.helm:
      name: front
      chart_ref: ./helm-frontend/frontend-chart
      release_namespace: default
      force: True
      disable_hook: True
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      values: 
        replicaCount: 1
        image:
          repository: changeme
          tag: latest
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: changeme
        env:
          BACKEND_URL: changeme
        ingress:
          enabled: true
          host: app.class-schedule.pp.ua
          path: /
          pathType: Prefix
          entryPoint: websecure
          tls:
            enabled: true
            secretName: tls-secret
      release_state: "{{ helm_release_state }}"
