- name: Install K3s server
  hosts: servers
  tasks:
  - name: Install fronend
    kubernetes.core.helm:
      name: front
      chart_ref: ./helm-frontend/frontend-chart
      release_namespace: default
      force: True
      disable_hook: True
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      values: 
        replicaCount: 1
        image:
          repository: "{{ image_repository }}"
          tag: "{{ image_tag }}"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: "{{ service_port }}"
        env:
          BACKEND_URL: '{{ BACKEND_URL }}'
        ingress:
          enabled: true
          host: app.class-schedule.pp.ua
          path: /
          pathType: Prefix
          entryPoint: websecure
          tls:
            enabled: true
            secretName: tls-secret
      release_state: "{{ helm_release_state }}"
  - name: Check frontend pods status
    shell: |
      kubectl get pods -n default -l app=frontend -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.phase}{"\n"}{end}'
    register: pod_status

  - debug:
      msg: "{{ pod_status.stdout }}"
